# App context configuration
server.port=${PORT:8082}

# Configure H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:pharmacydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Allow Spring Boot to auto-create database tables from your Entity classes
spring.jpa.hibernate.ddl-auto=update

# Enable the H2 web console (Optional debug tool available at /h2-console)
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true